### ISSUE TITLE
Compilation fails in Slackware-current

### ISSUE THREAD

**Issue by thegreyshadow** [stragulus/mp3blaster#3]
Hi stragulus! Thanks for mp3blaster, it's a program which I really appreciate.

I tried to build 3.2.6 but couldn't.. However, this is not an issue limited to 3.2.6 because I had the same error with 3.2.5.

Using: Slackware-current, with gcc 7.1
This is the relevant compilation output:
```
g++ -DHAVE_CONFIG_H -I. -I.. -I. -I/usr/include  -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT   -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -O2 -fPIC -MT bitwindow.o -MD -MP -MF .deps/bitwindow.Tpo -c -o bitwindow.o bitwindow.cc
mv -f .deps/bitwindow.Tpo .deps/bitwindow.Po
g++ -DHAVE_CONFIG_H -I. -I.. -I. -I/usr/include  -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT   -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -O2 -fPIC -MT huffmantable.o -MD -MP -MF .deps/huffmantable.Tpo -c -o huffmantable.o huffmantable.cc
huffmantable.cc:587:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘unsigned int’ inside { } [-Wnarrowing]
 };
 ^
huffmantable.cc:587:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘unsigned int’ inside { } [-Wnarrowing]
huffmantable.cc:587:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘unsigned int’ inside { } [-Wnarrowing]
huffmantable.cc:587:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘unsigned int’ inside { } [-Wnarrowing]
huffmantable.cc:587:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘unsigned int’ inside { } [-Wnarrowing]
huffmantable.cc:587:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘unsigned int’ inside { } [-Wnarrowing]
make[2]: *** [Makefile:382: huffmantable.o] Error 1
make[2]: Leaving directory '/tmp/SBo/mp3blaster-3.2.6/mpegsound'
make[1]: *** [Makefile:446: all-recursive] Error 1
make[1]: Leaving directory '/tmp/SBo/mp3blaster-3.2.6'
make: *** [Makefile:343: all] Error 2
```

I'd appreciate any hint that could make this build smoothly, since I would really like to try the new 3.2.6. Thanks in advance.

**Comment by willysr** [comment]
@thegreyshadow : you can try this patch in your SlackBuild:
```
--- a/audio/mp3blaster/mp3blaster.SlackBuild
+++ b/audio/mp3blaster/mp3blaster.SlackBuild
@@ -72,7 +72,7 @@ find -L . \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
 CFLAGS="$SLKCFLAGS" \
-CXXFLAGS="$SLKCFLAGS" \
+CXXFLAGS="$SLKCFLAGS -std=c++11 -Wno-narrowing" \
 ./configure \
   --prefix=/usr \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
```
tested on 3.2.6

**Comment by thegreyshadow** [comment]
Indeed. Now it works. Thanks Willy!
So in order to build with gcc 7.1 it's necessary to add -std=c++11 and -Wno-narrowing to the compiler flags.

**Comment by thegreyshadow** [comment]
Closing since it was fixed. Thanks

**Comment by ghost** [comment]
I got the same error - I'll lazily wait for the next release. :)

Sourceforge actually works pretty well as an archive of tarballs.
